name: Merge

on:
  push:
    branches:
      - feat/**

jobs:
  merge:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          python3 setup.py install
          export PYTHONHASHSEED=42
          pip3 install -r ./build_configs/linux/requirements.txt
          pyinstaller --distpath staking_deposit-cli-linux-arm64 ./build_configs/linux/build.spec;
          ls -al staking_deposit-cli-linux-arm64
          echo "${HOME}/staking_deposit-cli-linux-arm64/deposit" >> $GITHUB_PATH

      - name: Save staking-deposit-cli
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: staking_deposit-cli-linux-arm64/deposit
          name: staking-deposit-cli
          compression-level: 0
